version: "3.8"
services:

  spring-boot-app:
    build:
      context: 
        ./Backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://reservista.mysql.database.azure.com:3306/ReservistaDB
      SPRING_DATASOURCE_USERNAME: Reservista_Admin
      SPRING_DATASOURCE_PASSWORD: )Yg#EQE$
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    

  react-native-app:
    build:
      context: 
        ./Frontend
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"

    stdin_open: true
    tty: true
    depends_on:
      - spring-boot-app

#volumes:
#  mysql-data:
